batch_size: 65536
download_retries: 3
upload_retries: 3

firmzone_codes:
  coastal_v:
    - V
    - VE
  coastal_a:
    - A
    - AE
    - AH
    - AO
    - A99
    - AREA

found_type_map:
  "2": 2
  "4": 4
  "5": 5
  "7": 7
  B: 4
  BASEMENT: 4
  C: 5
  CRAWL: 5
  CRAWL SPACE: 5
  P: 2
  PIER: 2
  S: 7
  SLAB: 7
  SLAB ON GRADE: 7
  F: 5
  I: 5
  W: 5
